spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:8888"


#Configuración del actuator
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, health, info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

#Configuración de Cirucuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      catalog-post:
        allow-health-indicator-to-fail: false
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1500
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

#Configuración del mecanismo de reintentos
  retry:
    instances:
      catalog-post:
        max-attempts: 3
        wait-duration: 1000
        retry-exceptions:
          - feign.FeignException



