spring:
    datasource:
    # MySQL
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://${DB_HOST:localhost}:3306/movies?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                formate_sql: true
        show-sql: false

server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
